color0 #212830
color1 #fd4663
color2 #8fa7c2
color3 #9190c1
color4 #aa90c1
color5 #acbed2
color6 #aeadd1
color7 #f2f2f3
color8 #616971
color9 #fd4663
color10 #8fa7c2
color11 #9190c1
color12 #aa90c1
color13 #acbed2
color14 #aeadd1
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1e23
background            #1a1e23
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #212830
active_border_color   #8fa7c2
inactive_border_color #212830
url_color             #8fa7c2

active_tab_foreground   #1b1e22
active_tab_background   #8fa7c2
inactive_tab_foreground #afb2b6
inactive_tab_background #212830
cursor_trail_color      #afb2b6
